[package]
name = "viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ori = { git = "https://github.com/changecaps/ori", features = ["image", "font-awesome", "tracing"] }
